### ISSUE TITLE
Notification message when burn/blanking operation is complete (enhancement)

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#16]
Currently there is no way to tell if the burn or blanking operation has successfully completed, other than the cdrecord or mkisofs log. Another alternative may be to enable verbose mode.

**Comment by Vidrep** [comment]
BurnItNow indicates "Burning in progress..." even after the burn has been successfully completed. (see attached screenshot showing completed burn of a CD iso)

**Comment by Vidrep** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/13264393/19865557/556f914c-9f62-11e6-840d-f556d25c9b34.png)

**Comment by humdingerb** [comment]
The separator label informs of the status in the upcoming release.
