### ISSUE TITLE
BurnItNow does not build on x86_gcc2h

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#18]
Building BurnItNow on x86_gcc2 results in the following error message:

~/haikuports> haikuporter -S -j4 --get-dependencies --no-source-packages burnitnow
Checking if any package-infos need to be updated ...
        burnitnow-0.1.0 is still marked as broken on target architecture
Looking for stale dependency-infos ...
Warning: skipping burnitnow-0.1.0, as it is broken on the target architecture.
Error: No version of burnitnow can be built

Removing the "!" in the burnitnow recipe resolves the issue:
ARCHITECTURES="!x86_gcc2 x86 x86_64"

Tested as working on x86_gcc2 architecture.

**Comment by humdingerb** [comment]
Upcoming release builds fine.
