### ISSUE TITLE
What do the colors mean?

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/BurnItNow#21]
I am confused by all the colors at the bottom bar.  Usage instruction might be helpful to me :-) But that isn't working yet.  Could you do a simple tooltip on the bar for a simple summary of what it means?

**Comment by humdingerb** [comment]
I added the tool tip.
Summoning the help file does work, but only when BurnItNow comes in it's package which will put the help file where it's expected. It's in the Docs folder.
