### ISSUE TITLE
Scroll view status view

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/BurnItNow#23]
I think using a scroll view status view next to the horizontal scroll bar to show the % complete instead of filling the scroll view with list items for each new status would look cleaner (see Repositories preflet).  Do you foresee someone wanting to go back to review each status list item?
If the status view is too small, maybe provide another StringView or BStatusBar somewhere for the % complete and estimated completion time.

**Comment by humdingerb** [comment]
Having the scroll view with the complete mkisofs/cdrecord output isn't too bad. If something goes wrong, people can see exactly what was the matter.
I do agree, that the actual progress of building/burning could be more condense.
I've thought about erasing the last percentage line before adding the new, but I haven't figured out how to do that with the BTextView...

**Comment by Perelandra0x309** [comment]
This line is very long, can it be broken up?

Last chance to quit, starting real write in 9 seconds.   8 seconds.   7 seconds.   6 seconds.   5 seconds.   4 seconds.   3 seconds.   2 seconds.   1 seconds.   0 seconds. Operation starts.cdrecord: WARNING: Drive returns wrong startsec (0) using -150

**Comment by Perelandra0x309** [comment]
Ha, this was a driect copy and paste from the text view.  Those ? didn't show up until a submitted the comment. Let's try another sample:

Vendor_info    : 'TSSTcorp'
Identifikation : 'CDDVDW TS-H653Z '
Revision       : 'HD00'
Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.

**Comment by Perelandra0x309** [comment]
Hmm, maybe you can use those special symbols to detect when to make a new line?

**Comment by humdingerb** [comment]
The CommandReader feeds me always one line at a time. I assume the whole "Last chance to quit,..." line appears all at once, right?
Then I don't think there's much that can be done. But, since we can't (or at least I don't know how) abort the command (cdrecord, mkisofs...) once it's set off, the whole line could be just ommmitted.

Come to think of it, we should use a "gracetime=2" to save us 8 seconds of waiting.

**Comment by humdingerb** [comment]
I implemented a simple - in my amateurish ways - parser of the command output with f1acd29.
Next I'll look into exctracting the percentage and ETA to display in a notification.
Think we can close this ticket?

**Comment by humdingerb** [comment]
gracetime can't be < 2 seconds, says the man page.

Not sure how to extend BTextView. Small time coder here... :)
I have the parsing in a separate function that I reuse for all tabs. I figure, as long as the parsing is limited to only a few strings, it's fast enough that we don't need to do separate string tests for the different tabs.
But feel free to give hints or PRs. :)
