### ISSUE TITLE
Quitting after building but before burning

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/BurnItNow#25]
If I finish building image then quit before burning, the burnitnow_data.iso is left over in /boot/system/cache

**Comment by humdingerb** [comment]
There's the item "Clear cache on quit" under "Settings" (which I wonder if we should rename "Cache" as it all pertains to the Cache and the "Open cache folder" isn't a setting at all...).
Some people might want to keep the generated ISO.
