### ISSUE TITLE
Detect mkisofs before building image

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/BurnItNow#26]
I understand that as an hpkg there will be a dependency on cdrecord/mkisofs, however it is possible that someone may build from source.  Without mkisofs installed the build step just stalls.  This binary should be confirmed to exist before building the disc image.  If it does not exist display a warning alert.

**Comment by humdingerb** [comment]
I feel making this effort would ignore an advantage we have because of package management. Listing dependencies in the github readme for people compiling from source is OK, of course.

**Comment by Perelandra0x309** [comment]
True package management is nice.  However there is always the possibility that a package gets broken.

**Comment by humdingerb** [comment]
How can a package be broken that the dependency info gets lost? Or do you mean somebody could mess up the haikuporter recipe? That would be a botched release that will have to be fixed anyway.
I still don't think we need to code for that eventuality. I added the info to the GitHub ReadMe.md with 4865cc8
