### ISSUE TITLE
Freedb alternative 

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#33]
Freedb, the community-generated database of music CD metadata, is shutting down on March 31, 2020. 
Amend CompilationCloneView.cpp:

fBurnerThread->AddArgument("cdda2wav")
				->AddArgument(device)
				->AddArgument("cddbp-server=gnudb.gnudb.org")
				->AddArgument("cddbp-port=8880")
				->AddArgument("cddb=1")
				->AddArgument("speed=4")
				->AddArgument("-vall")
				->AddArgument("-B")
				->AddArgument("-x")
				->AddArgument("-Owav")
				->AddArgument(wavPath)
				->Run();
		}

**Comment by humdingerb** [comment]
Wanna create a PR for that, or rather not? :)
What about that "speed=4" argument? We usually use the speed slider value...
Otherwise, I assume you tested the above and we can published a bumped version after the merge.

**Comment by scottmc** [comment]
Could also add support for getting info from musicbrainz.  See https://github.com/HaikuArchives/ArmyKnife for example.

**Comment by humdingerb** [comment]
@Vidrep, can you check #34 to see if it works. I have no CD drive handy.

I kept the original parameters for cdda2wav but added your cddb lines and the -x parameter. I didn't add the "speed" parameter.

**Comment by scottmc** [comment]
What do you do in BurnItNow that will trigger a cddb search?  Audio tab only has the Add... button ungreyyed out.  The clone disc tab just gives a message saying to copy the WAV files to the hard drive, and then use audio cd to burn those to disc.  Neither place is looking up the file names, that is handled by Haiku itself in naming the wav files.  Am I missing something here?

**Comment by Vidrep** [comment]
You’re correct. The cddb lookup was fixed here: https://git.haiku-os.org/haiku/commit/?id=0071f2c47796091551aa3f0bcd09f6443e7fc5f3
However, we now have another problem. Cdda2wav isn’t working on recent builds. Tested as working on hrev55608 x86_gcc2h, but not on more recent revisions. Perhaps the recent update to gcc11?

**Comment by humdingerb** [comment]
OK, since the default cddb server has been fixed, close this issue and PR #34
