### ISSUE TITLE
cdda2wav clone not working on 64 bit nightly

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#35]
Tested clone function as working on 64 bit Beta (hrev55181+62) with both gcc8 and gcc11 builds.
On 64 bit nightly (hrev55662) it fails with the following error:

samplefile size will be 423515276 bytes.
recording 2400.8800 seconds stereo with 16 bits @ 44100.0 Hz ->'/boot/system/cache/burnitnow_clone_wavs/'...
percent_done:
  0%cdda2wav: clone_area failed
cdda2wav: Child reader sem request failed.

W Child exited with 9

**Comment by waddlesplash** [comment]
Check your syslog. This is probably due to cdda2wav never having set B_CLONABLE_AREA.

**Comment by Vidrep** [comment]
From the syslog for that session:

KERN: team "cdda2wav" (2280) attempted to clone area "shmfifo" (27566)!
KERN: ahci: Probe: port 2 link speed 1.5Gb/s
KERN: ahci: sata_request::finish ATA command 0xa0 failed: status 0x51, error 0x54
KERN: ahci: sata_request::finish ATAPI packet d8 00 00 00 00 00 00 00 00 37 00 00 00 00 00 00 (len 12)
KERN: raw_command: 
KERN: Last message repeated 7 times.
KERN: SCSI -- copy_sg_data: buffer = 0xffffffff803b2a10, virt_addr = 0x7bcd1540, bytes = 36, to_buffer = 1
KERN: SCSI -- copy_sg_data: buffer = 0xffffffff803b2a10, virt_addr = 0x7bcd1540, bytes = 36, to_buffer = 0
KERN: raw_command:

**Comment by Vidrep** [comment]
I have narrowed down the issue to between hrev55625 (working) and hrev55632 (not working). Cdrecord is similarly broken. Attempting to burn any kind of disc results in a crash.

**Comment by humdingerb** [comment]
That would suggest that @waddlesplash is right on the money.
[hrev55632](https://git.haiku-os.org/haiku/commit/?id=049eb4cb89e83bc8ee46f9fbb8b2b33607e864a5) "_libroot/os: Remove B_CLONEABLE_AREA protection check._" seems to be the culprit.

No idea how that is fixed, of course...

**Comment by waddlesplash** [comment]
https://github.com/Distrotech/cdrtools/blob/8adb0d06e070464f13d017b1de7187bf23dacd87/cdrecord/fifo.c#L363

B_CLONEABLE_AREA needs to be added to the protection flags here.

**Comment by humdingerb** [comment]
I patched cdrecord locally, but cannot test.
@Vidrep, could you try it out before I create a PR at haikuports? -> http://0x0.st/-hXO.hpkg [1.7 MiB]

**Comment by humdingerb** [comment]
FYI this is the diff:

```
diff -up cdrtools-3.02/cdrecord/fifo.c cdrtools-3.02/cdrecord/fifo.c
index 95e4846..a248cb8 100644
--- cdrtools-3.02/cdrecord/fifo.c
+++ cdrtools-3.02/cdrecord/fifo.c
@@ -366,7 +366,7 @@ mkbeosshm(size)
 	faio_aid = create_area(faio_name, &faio_addr,
 			B_ANY_ADDRESS,
 			size,
-			B_NO_LOCK, B_READ_AREA|B_WRITE_AREA);
+			B_NO_LOCK, B_READ_AREA|B_WRITE_AREA|B_CLONEABLE_AREA);
 	if (faio_addr == NULL) {
 		comerrno(faio_aid,
 			_("Cannot get create_area for %d Bytes FIFO.\n"), size);

```

**Comment by humdingerb** [comment]
@Vidrep, following waddlesplash's comment on the closed Haiku ticket, I patched shmfifo.c as well.
Here's a test HPKG: http://0x0.st/-hqJ.hpkg

These are the changes applied:

```
diff --git a/cdda2wav/semshm.c b/cdda2wav/semshm.c
index 36f75c8..474b960 100644
--- a/cdda2wav/semshm.c
+++ b/cdda2wav/semshm.c
@@ -557,7 +557,7 @@ shm_request(size, memptr)
 		B_ANY_ADDRESS,		/* type of address constraint */
 		size,			/* size in bytes (multiple of pagesize) */
 		B_NO_LOCK, /* B_FULL_LOCK, */ /* memory locking */
-		B_READ_AREA | B_WRITE_AREA);	/* read and write permissions */
+		B_READ_AREA | B_WRITE_AREA)|B_CLONEABLE_AREA;	/* read and write permissions */
 
 	if (aid < B_OK)
 		comerrno(aid, _("create_area() failed\n"));
diff --git a/cdrecord/fifo.c b/cdrecord/fifo.c
index 95e4846..3216c87 100644
--- a/cdrecord/fifo.c
+++ b/cdrecord/fifo.c
@@ -366,7 +366,7 @@ mkbeosshm(size)
 	faio_aid = create_area(faio_name, &faio_addr,
 			B_ANY_ADDRESS,
 			size,
-			B_NO_LOCK, B_READ_AREA|B_WRITE_AREA);
+			B_NO_LOCK, B_READ_AREA|B_WRITE_AREA|B_CLONEABLE_AREA);
 	if (faio_addr == NULL) {
 		comerrno(faio_aid,
 			_("Cannot get create_area for %d Bytes FIFO.\n"), size);
@@ -390,7 +390,7 @@ beosshm_child()
 	 * using the pointer in the child. So we noe use B_EXACT_ADDRESS.
 	 */
 	faio_aid = clone_area(faio_name, &faio_addr,
-			B_EXACT_ADDRESS, B_READ_AREA|B_WRITE_AREA,
+			B_EXACT_ADDRESS, B_READ_AREA|B_WRITE_AREA|B_CLONEABLE_AREA,
 			faio_aid);
 	if (bufbase != faio_addr) {
 		comerrno(EX_BAD, _("Panic FIFO addr.\n"));

```

**Comment by Vidrep** [comment]
After a lot of disc burning with a variety of media I have concluded that the first patch to fifo.c is sufficient to allow data disc, audio cd, image file, audio/video dvd, and blank rw to function normally without crashing.
The subsequent patches however did not fix the issue with cloning using cdda2wav. That remains an issue.
For now, push the first patch, as cloning is disabled anyhow in BurnItnow.

**Comment by waddlesplash** [comment]
@humdingerb Your patch has a typo, the B_CLONEABLE_AREA is outside the ) and not inside as it should be.

**Comment by humdingerb** [comment]
Argl! That's embarrassing... My eyesight keeps deteriorating. :}
One more try with corrected bracket: http://0x0.st/-hLg.hpkg

**Comment by Vidrep** [comment]
The last patch resolves the issues discussed and was pushed to HaikuPorts. Closing as fixed.
