### ISSUE TITLE
Typos in source code

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#36]
AudioList.cpp
L#471 	char nummber[4];
L#472 	snprintf(nummber, sizeof(nummber), "%" B_PRId32, fTrack + 1);
L#473	track.Append(nummber);

Shouldn't it be (number)?

CommandPipe.h
L#79 	// Stardard append operators, if you use pointers to a BCommandPipe,

Should be //Standard

CompilationDataView.cpp
L#33 "Tab lable"
Should be "Tab label"

**Comment by humdingerb** [comment]
I'll leave the "Tab lable", because  it's not visible in the GUI but would alter the catkeys resulting in needless translation work. Thanks!
