### ISSUE TITLE
LLVM static code analysis - 2 bugs found

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#37]
[scan-build-2021-12-11-110617-2229-1.zip](https://github.com/HaikuArchives/BurnItNow/files/7697935/scan-build-2021-12-11-110617-2229-1.zip)

**Comment by humdingerb** [comment]
I fixed the ones in BurnItNow, but leave the one complaining about a system header. That's a Haiku issue, and I suspect a false positive anyway.
